### PR TITLE
added PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by mohittk**
added PULL_REQUEST_TEMPLATE.md file, by adding suitable and important considerations for the contributers.

### CODE REVIEW

**Comment by mohittk** [comment]
Hey bro! Could you please label this PR as Hacktoberfest-accepted?

**Comment by SugatoBagchi** [comment]
@mohittk Please mention the issue which solves this PR.
Also, please verify you have solved the issue completely. Then only it will be accepted as hacktoberfest-accepted

**Comment by mohittk** [comment]
> @mohittk Please mention the issue which solves this PR. Also, please verify you have solved the issue completely. Then only it will be accepted as hacktoberfest-accepted

Yes sir, you can checkout the PULL_REQUEST_TEMPLATE.md
Issue #8  solved!

**Comment by SugatoBagchi** [comment]
@mohittk Please make a code of conduct as well.

**Comment by mohittk** [comment]
> @mohittk Please make a code of conduct as well.

Sure! will do.

**Pull request merged**
